### ISSUE TITLE
Share Crew Recruitment Applications

### ISSUE THREAD

**Issue by Robert-Watts** [adam-rms/adam-rms#115]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to allow other users, who are not the project manager to view the applications. For example, if the project manger is mentoring a new pm, or for something like MiD, it would be useful for both the PM and prod team can view applications without the rest of the exec seeing them.

**Describe the solution you'd like**
A box that allows you to select multiple users. Maybe they get an email to tell them they can view that projects recruitment. 

**Describe alternatives you've considered**
We used to do this on google forms, where multiple people would look at the form. It was useful.

**Comment by Jbithell** [comment]
https://github.com/bstudios/adam-rms/issues/116 was, in a sense, related
