### ISSUE TITLE
Migration issues

### ISSUE THREAD

**Issue by nathanbillis** [adam-rms/adam-rms#117]
When running `php vendor/bin/phinx migrate` for the first time the following error occurs:

```
 == 20210529185811 AddFileShareAction: migrating
START TRANSACTION;
 -- bulkinsert('instanceActions')
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`adamrms`.`instanceActions`, CONSTRAINT `categories_fk` FOREIGN KEY (`instanceActionsCategories_id`) REFERENCES `instanceActionsCategories` (`instanceActionsCategories_id`) ON DELETE CASCADE O) 
```

**Comment by nathanbillis** [comment]
Work around is to migrate, seed then migrate again

**Comment by Jbithell** [comment]
Looks like by having values in a migration we are hitting this issue. The solution might be to drop this change into the seed also, and then check the foreign key exists in the migration

**Comment by Robert-Watts** [comment]
![image](https://user-images.githubusercontent.com/11817698/130368307-20e961e4-7f63-46cc-aaf3-ad98239ba776.png)

**Comment by Robert-Watts** [comment]
Getting same issue

**Comment by nathanbillis** [comment]
@Robert-Watts did the migrate, seed, migrate workaround work for you?

**Comment by Robert-Watts** [comment]
Yes it did 😀
