### ISSUE TITLE
[FEATURE] Export

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#178]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It would be useful to have a way of exporting & inporting instance data, to better support self-hosting and also working with instances locally

### Describe the solution you'd like

Export all data for an instance (in a propietary format most likely) and then re-import it

### Describe alternatives you've considered

`mysqldump` or the like

**Comment by Robert-Watts** [comment]
> Which secret are you thinking of?

I got confused and thought the JWT secret in the env file was used a a password salt. Ignore that part.

**Comment by Jbithell** [comment]
This can be done with `mysqldump`, and using the mysql delete command to remove other instances. Access tokens etc can then be deleted by truncating those tables, but this is a quick manual process.

**Comment by Jbithell** [comment]
Closing on basis can be completed with mysqldump

**Comment by Jbithell** [comment]
> This can be done with `mysqldump`, and using the mysql delete command to remove other instances. Access tokens etc can then be deleted by truncating those tables, but this is a quick manual process.

![image](https://user-images.githubusercontent.com/8408967/208251870-3020f00c-3c36-4dce-a6fc-e3f4b2b46ab6.png)

Based on the schema, my take is that when migrating from one server to anohter, delete all instances except the one you want to migrate.

Next, delete all users where userInstances = null for their userid

Then, remove any `assetsBarcodes` without an instanceId set

Truncate:
- [x] auditLog
- [x] authTokens
- [x] emailSent
- [x] emailVerificationCodes
- [x] loginAttempts
- [x] passwordResetCodes

@cherry-john could you add the above to https://github.com/adam-rms/website/pull/21 next time you're looking at it?

**Comment by Jbithell** [comment]
Other thing we would need to think about are files uploaded ... what would be done with those
