### ISSUE TITLE
[BUG] Can't add assets to a second subproject.

### ISSUE THREAD

**Issue by chriscn** [adam-rms/adam-rms#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Video](https://www.youtube.com/watch?v=TqidIUr7xLg) explains what the issue is. I may be missing something blinding obvious.

### Expected Behavior

Being able to add assets to subprojects.

### How are you accessing AdamRMS?

```markdown
- OS: macOS Big Sur Version 11.5.2 (20G95)
- Browser: Chrome
- Version:
```

**Comment by cherry-john** [comment]
Issue seems to be sub-projects are not listed correctly in warehouse/asset list.
Only seems to be visible if there are assets associated with that sub-project

**Comment by Jbithell** [comment]
@chriscn there's been some updates in this area by @cherry-john - are you still able to reproduce this?

**Comment by chriscn** [comment]
> @chriscn there's been some updates in this area by @cherry-john - are you still able to reproduce this?

I don't have access to a local envrionment at this time. For TechSoc's RMS the fresher's fair project reproduces this issue.
