### ISSUE TITLE
[BUG] Copying and pasting comments includes metadata

### ISSUE THREAD

**Issue by chriscn** [adam-rms/adam-rms#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1 (Default)

### Current Behavior

<img width="802" alt="Screenshot 2021-10-26 at 16 28 47" src="https://user-images.githubusercontent.com/25829276/138911442-54f8e0b5-d79a-4b9c-80cf-caccc61b773b.png">

### Expected Behavior

The HTML tags to be used. Assuming this is prevent against an XSS attack.

### Steps To Reproduce

1. Go onto Technical Theatre AdamRMS
2. Press CHMS Rigging / Rigging Training
3. See the comment

**Comment by Jbithell** [comment]
@cherry-john is there a particular reason we went with Markdown for this feature? Could we just use the existing editor we use for CMS etc. or is that too heavy?

**Comment by cherry-john** [comment]
I can't remember if there was, but there must have been. Happy to use the existing editor instead if that will solve this issue

**Comment by Robert-Watts** [comment]
From memory @Jbithell when saving the html in the dB the html was stripped so it never displayed correctly but John looked at it properly
