### ISSUE TITLE
Add date and author to LICENSE.

### ISSUE THREAD

**Issue by chriscn** [adam-rms/adam-rms#254]
https://github.com/bstudios/adam-rms/blob/c7a6250c63e2fefecb7bffbe0c4b7a6d7c5f4f4b/LICENSE#L633

**Comment by Jbithell** [comment]
Unless I'm mistaken you don't normally update this line, you copy it and update it in places where you've copied it to?

Such as https://github.com/bstudios/adam-rms#licence
