### ISSUE TITLE
[BUG] Notes options formatting is broken

### ISSUE THREAD

**Issue by cherry-john** [adam-rms/adam-rms#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

V1.77.3

### Current Behavior

![image](https://user-images.githubusercontent.com/54247748/148210941-adc74d16-1347-430d-b49d-feb0e554ced0.png)

### Steps To Reproduce

1. Go to a project's Files
2. Create or edit a file
3. See funky formatting

### How are you accessing AdamRMS?

https://www.whatsmybrowser.org/b/ZDPOR

**Comment by Jbithell** [comment]
![image](https://user-images.githubusercontent.com/8408967/148213158-d242519a-2dea-49b5-ae28-f4b08aabe08f.png)

Works for me https://www.whatsmybrowser.org/b/AFZ1C

**Comment by cherry-john** [comment]
Just tried on a different device and it's working there, will close this as I'm assuming it's a cache issue

**Comment by Jbithell** [comment]
Is it still doing it on original device?

**Comment by cherry-john** [comment]
No, cleared my cache and it stopped
