### ISSUE TITLE
[BUG] assets/data.php endpoint fatal error

### ISSUE THREAD

**Issue by cherry-john** [adam-rms/adam-rms#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.77.3

### Current Behavior

![270647752_3139274599732644_572766754555006918_n](https://user-images.githubusercontent.com/54247748/148392219-88118727-603a-43c1-b456-f9d8b8d6de1d.png)

### How are you accessing AdamRMS?

https://www.whatsmybrowser.org/b/ZDPOR

### Anything else?

Found in a dev build and replicated in a prod build

**Comment by Jbithell** [comment]
Background to this is that for projects that include assets from another business the project view fails
