### ISSUE TITLE
[BUG] Error Code 500 when attempting to access an archived project

### ISSUE THREAD

**Issue by chriscn** [adam-rms/adam-rms#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.77.3

### Current Behavior

Attempting to access the [Chicago](https://dash.adam-rms.com/project/?id=5) archived project leads to a HTTP 500 Error

### Expected Behavior

Ability to view archived projects.

### Steps To Reproduce

1. Go to [url](https://dash.adam-rms.com/project/?id=5)
2. See 500 Error

### How are you accessing AdamRMS?

https://whatismybrowser.com/w/334WP43

### Anything else?

Was wanting to view ERN from last year in preparation in meeting Rob this evening.

**Comment by chriscn** [comment]
Not sure if related to #291

**Comment by chriscn** [comment]
Update seems to be fixed, happy for this to be closed now. Maybe a server misconfiguration.

**Comment by cherry-john** [comment]
This was due to #291, so will close
