### ISSUE TITLE
[FEATURE] Improve signup form

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#295]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It's step based which is annoying, and confusing for end user. 

Password requirements are unclear.

EMail verification should take place at another step

### Describe the solution you'd like

User should be able to sign up in a more accessible way. A better designed, clear simpler form is needed

**Comment by cherry-john** [comment]
@adam-rms/senior-maintainers I'd say this was covered with the changes to focus on google auth, or was the whole bCMS login planned to be tweaked too?
