### ISSUE TITLE
[BUG] 404 on edit user page

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#296]
### Have you contacted the support team about this?

No - I'm an experienced maintainer and I've found/suspect I've found root cause

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.77.4

### Current Behavior

[https://dash.adam-rms.com/user.php?id=0000](https://dash.adam-rms.com/user.php?id=[userid]) is giving a 404.

### How are you accessing AdamRMS?

https://www.whatsmybrowser.org/b/I256W

**Comment by cherry-john** [comment]
What should this do? Display a user's profile?
