### ISSUE TITLE
[FEATURE] Asset Search & Filtering .... v3!

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#304]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Wow we do a lot of versioning on this project don't we!

@Robert-Watts  doesn't like the current asset selector, and it has a fair few issues.

Should we start again and think about something different - if so what should we do

### Describe the solution you'd like

Ideas include putting params in the url to help people share search terms 

Favourite searches?

Move the search bar to where the left bar is currently? How do we make that work on mobile?

**Comment by cherry-john** [comment]
First thought on this is moving the asset search to be on a per project basis. i.e adding a tab to each project for "Add assets", and renaming current asset page to "Asset List". I would also consider retiring "asset dispatch" as it's overcomplicated and not convinced of it's use anymore
