### ISSUE TITLE
[BUG] File Sharing not working

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#306]
### Have you contacted the support team about this?

Yes - Support then came back to me and suggested I report it here

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1

### Current Behavior

File sharing is returning 404s

**Comment by chriscn** [comment]
<img width="509" alt="Screenshot 2022-01-23 at 17 28 45" src="https://user-images.githubusercontent.com/25829276/150690406-a86633e8-1147-4216-af61-f382d9925a0b.png">

How I imagine that support call going:
![](https://i.redd.it/bekphnqftcb41.jpg)

**Comment by Jbithell** [comment]
I can't actually reproduce this @cherry-john - I can confirm that the link you generated is broken, but hitting "regenerate" works. For whatever reason that original hash was not a valid SHA2-256 - it was far too short.

**Comment by cherry-john** [comment]
Happy to close this in that case!
