### ISSUE TITLE
[FEATURE] Subprojects track the status of their parent project

### ISSUE THREAD

**Issue by chriscn** [adam-rms/adam-rms#307]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Having a project with a large number of subprojects requires the end user to manually all update them as it changes status.

### Describe the solution you'd like

When the main project's status is updated, it should check all the subprojects if they had the same status at the parent project it should be updated. 

This allows subprojects to both be updated with the main project however you can manually change them and not have to worry about them being reupdated.

**Comment by Jbithell** [comment]
I like the idea.

From a documentation perspective would it make more sense to have a setting on a sub project of "follows parent status"

**Comment by chriscn** [comment]
> I like the idea.
> 
> From a documentation perspective would it make more sense to have a setting on a sub project of "follows parent status"

Yeah that is a good idea, I believe the default should be true to follow the parent status. Is this something that could be implemented?
