### ISSUE TITLE
[FEATURE] Accountless Crew Recruitment

### ISSUE THREAD

**Issue by cherry-john** [adam-rms/adam-rms#317]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The current crew recruitment system is great, but a barrier to entry for new members of the society due to a steep learning curve with the RMS, even with a good user guide.

### Describe the solution you'd like

Changes to the recruitment system, including a public signup page that just accepts emails.
The public signup form could also recognize existing users email addresses and link their account to the recruitment.

**Comment by Jbithell** [comment]
Great idea John - I've split this into two at https://github.com/adam-rms/adam-rms/issues/318

**Comment by Jbithell** [comment]
Could you share a bit more of the user journey/story and what bits of the process people are struggling with?

At the moment clicking "login to apply" takes you to a login page, selecting sign-in with google logs your account in, and then takes you straight to the crew recruitment page. The only other option I can envisage as more friendly would be to let you fill out an application direct from the public sites page, and then ask you to "click the link in the email" to submit the application.

**Comment by cherry-john** [comment]
I'm not entirely certain of how it should work. Some sort of anonymous form for those without accounts would help get people signing up.
Potentially tracking the button clicked on the public site as you log in, so you apply to that role after log in?

**Comment by Jbithell** [comment]
So showing the modal based on what was clicked before login?

**Comment by cherry-john** [comment]
Yeah? feel like it offers a more seamless application process
