### ISSUE TITLE
[BUG] total users being leaked

### ISSUE THREAD

**Issue by Robert-Watts** [adam-rms/adam-rms#322]
### Have you contacted the support team about this?

Yes - Support then came back to me and suggested I report it here

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

The latest

### Current Behavior

Total users is probably all users not just the users in the business 
![Screenshot_20220316-160316_Chrome](https://user-images.githubusercontent.com/11817698/158655268-9f77a288-b633-449d-8b79-59e6291524a0.jpg)

### Expected Behavior

Just business users

### Steps To Reproduce

Go home page 

### Anything else?

No.

**Comment by Jbithell** [comment]
Just to note for the issue that this wasn't leaking extra numbers or anything - just counting archived users accidentally
