### ISSUE TITLE
@Jbithell This just thrown an error in production

### ISSUE THREAD

**Issue by Robert-Watts** [adam-rms/adam-rms#330]
@Jbithell This just thrown an error in production

_Originally posted by @Robert-Watts in https://github.com/adam-rms/adam-rms/pull/301#discussion_r841237887_

**Comment by Robert-Watts** [comment]
am out right now can look at later if someone else does not get their first

**Comment by Robert-Watts** [comment]
![image](https://user-images.githubusercontent.com/11817698/161435091-20596f6f-07a3-40f8-8840-3cef07371991.png)

**Comment by Jbithell** [comment]
Having a look
