### ISSUE TITLE
[FEATURE] UoY Semesterisation 

### ISSUE THREAD

**Issue by Robert-Watts** [adam-rms/adam-rms#347]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

@cherry-john pointed out that when semesterisation happens at the uni, the calendar week numbers will stop working.

### Describe the solution you'd like

Some investigation will be need on how the week numbers are counted and a solution implemented.

### Describe alternatives you've considered

Moving to a different uni, decided against it in the end.

**Comment by Jbithell** [comment]
Why will they stop working - do semesters not have week numbers?

**Comment by cherry-john** [comment]
So we've not had full confirmation of this yet, but it looks like semesters will have reading weeks that are a break in the week numbers - ie week6, week7, reading week, week8, week9

**Comment by Jbithell** [comment]
That is disgustingly cursed

**Comment by cherry-john** [comment]
Have a horrible spreadsheet view of the expected timetables :)
https://sites.google.com/york.ac.uk/change-programme/modularisation-semesterisation/attendance-pattern

**Comment by chriscn** [comment]
That is a nicer graphic than the University put together, did you make it @Jbithell? You should do consultancy ;-)

**Comment by cherry-john** [comment]
Luckily enough, in V5 of this library there is a hook we can use to just edit the week number content
