### ISSUE TITLE
[BUG] Project error messages formatting looks incorrect

### ISSUE THREAD

**Issue by cherry-john** [adam-rms/adam-rms#369]
### Have you contacted the support team about this?

No - I'm an experienced maintainer and I've found/suspect I've found root cause

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.83.4

### Current Behavior

![image](https://user-images.githubusercontent.com/54247748/176404001-0c2f1d5c-fcc5-4d3c-8dc2-c7b4a4442948.png)

Asset not locked message formatted incorrectly

### How are you accessing AdamRMS?

https://www.whatsmybrowser.org/b/Z015M

**Comment by Jbithell** [comment]
The message also makes little to no sense
