### ISSUE TITLE
Do you answer emails? Trying to make a business account.

### ISSUE THREAD

**Issue by swcrazyfan** [adam-rms/adam-rms#394]
Hello! I've tried multiple emails on your site, but no one ever replies. How can I create a business account? I am the drama teacher at my school, and I'd love to experiment with using your software for our drama and theater tech.

You guys are doing a wonderful job with this software!

Thanks

**Comment by Jbithell** [comment]
Thanks for getting in touch @swcrazyfan apologies for the delay - we have replied to your ticket now. I will close this issue, but feel free to open one if you are having issues getting docker setup
