### ISSUE TITLE
[BUG] CORS Errors on PDF generation

### ISSUE THREAD

**Issue by adamskrz** [adam-rms/adam-rms#416]
### Have you contacted the support team about this?

No - I have steps to reproduce this issue, and I think I know what's causing it

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.93.1

### Current Behavior

When a new invoice or quote PDF is made, "Generating PDF, please wait..." is shown, but a PDF is not created. 
Checking the browser debugger shows a 'CORS Missing Allow Origin' error caused by the GET request to the instance logo, which then leads to an uncaught TypeError in '[URLBrowserResolver.js:26:12](webpack://pdfmake/src/browser-extensions/URLBrowserResolver.js)'

### Expected Behavior

A PDF should be generated.

### How are you accessing AdamRMS?

Tested on Firefox and Microsoft Edge

**Comment by Jbithell** [comment]
Thanks for reporting @adamskrz - we've had a look and this is an intermittent issue with business logos. Please untick the option for the logo and generate the invoice again. We should have a full resolution early next week.

**Comment by adamskrz** [comment]
Currently working again but will wait until @Jbithell says it's fully resolved!

**Comment by Jbithell** [comment]
Thanks @adamskrz for your patience, this was an intermittent issue which we were unable to diagnose as it appears to be related to something deep within the PDF library relating to CORS preflights. 

I have used an alternative approach here that downloads the logo on the server and serves it as a data-uri which seems to be working well now
