### ISSUE TITLE
[FEATURE] Add payment pending as a project status type

### ISSUE THREAD

**Issue by chriscn** [adam-rms/adam-rms#424]
After speaking with the E&H Manager here at TechSoc, he suggested that we should have a payment pending status for when the invoice is sent but we are waiting for the client to send us payment. 

Keeping the class as secondary.

**Comment by Jbithell** [comment]
Please see discussion in attached PR

**Comment by Jbithell** [comment]
The hard work is now done, as project statuses are specific to each instance. The next step is to develop a user interface to allow these to be edited.
