### ISSUE TITLE
[BUG] Asset Barcode generation has issues with multiple barcodes

### ISSUE THREAD

**Issue by cherry-john** [adam-rms/adam-rms#439]
### Have you contacted the support team about this?

No - I'm an experienced maintainer and I've found/suspect I've found root cause

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.96.2

### Current Behavior

There appears to be an issue with multiple barcodes being printed on one sheet using the inbuilt barcode generation tool. Also the length tags/colours are not always shown even when the option is enabled and assets have values

![image](https://user-images.githubusercontent.com/54247748/213864008-ffc0c5d4-8a97-4fa7-81b4-1cf4fe380e59.png)

Reported by Jamie Waters ([Judoguy12](https://github.com/orgs/yorktechsoc/people/Judoguy12))

### How are you accessing AdamRMS?

https://www.whatsmybrowser.org/b/GU0IB

**Comment by Jbithell** [comment]
Thanks for spotting this @Judoguy12
