### ISSUE TITLE
[BUG] Cannot reuse asset tag of deleted asset

### ISSUE THREAD

**Issue by markspolakovs** [adam-rms/adam-rms#505]
### Have you contacted the support team about this?

No - I have steps to reproduce this issue, and I think I know what's causing it

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

DEV

### Current Behavior

If an asset is deleted, its asset tag can never be reused, which is problematic especially if one is incorrectly deleted by accident. Not being able to reuse archived tags makes sense, but having this also apply to deleted ones is problematic.

### Expected Behavior

After deleting an asset, you should be able to reuse its asset tag on another asset.

### Steps To Reproduce

1. Create two assets (`MP-TEST-1` and `MP-TEST-2`)
2. Delete `MP-TEST-1`
3. Attempt to change the asset tag of `MP-TEST-2` to `MP-TEST-1`
4. 
![image](https://github.com/adam-rms/adam-rms/assets/2904440/5f452756-5190-4253-8ad1-2867d2f547bd)

### How are you accessing AdamRMS?

https://www.whatsmybrowser.org/b/YKCEJ

### Anything else?

Ran into this during the YSTV import - deleted an imported asset with the intention of changing a pre-existing one's tag to replace it.

**Comment by cherry-john** [comment]
Confirmed same behaviour on current dash version(61ef36d)

**Comment by Jbithell** [comment]
I'm thinking its as simple as just adding a "where not deleted" here 
https://github.com/adam-rms/adam-rms/blob/c285a49a01f70593faaa6c14b7aee13015c57dc5/html/admin/api/assets/editAsset.php#L35

I can't personally think of any unintended consequences with that
