### ISSUE TITLE
[PROPOSAL] End support for the AdamRMS v1 App

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#589]
Some routine evaulation of logins to the [AdamRMS App](https://github.com/adam-rms/app) reveals that it has no consistent/regular users. This discussion proposes to remove support for it, removing it from app stores, before the start of June.

Running the SQL query `SELECT authTokens_created, authTokens_deviceType, users_username, (SELECT instances_name FROM userInstances LEFT JOIN instancePositions on userInstances.instancePositions_id = instancePositions.instancePositions_id LEFT JOIN instances ON instancePositions.instances_id = instances.instances_id WHERE users_userid = users.users_userid AND userInstances_archived IS NULL AND userInstances_deleted = 0 LIMIT 1) FROM authTokens LEFT JOIN users on authTokens.users_userid = users.users_userid WHERE authTokens_type = 'app-v1' ORDER BY authTokens_created DESC;` on the production database (uses the filter setup in https://github.com/adam-rms/adam-rms/commit/cc41bdf8305e3bbebaf4f884d1dba2a7b552d37f) reveals the following data (usernames and instance names have been replaced by identifiers, duplicate logins by the same user within the space of a few minutes have been removed, and my logins associated with testing the app have been removed):

| Token Created       | Token Device Type  | User Identifier | User's primary Instance Identifier |
|---------------------|--------------------|-----------------|---------------------|
| 2024-01-05 22:35:27 | App OAuth - Google | User A          | Instance A          |
| 2023-12-09 13:29:42 | App OAuth - Google | User B          | Instance A          |
| 2023-11-22 20:08:38 | App OAuth - Google | User C          | Instance B          |
| 2023-11-20 00:35:01 | App OAuth - Google | User C          | Instance B          |
| 2023-11-14 22:36:48 | App OAuth - Google | User D          |                     |
| 2023-11-08 00:16:52 | App OAuth - Google | User E          | Instance A          |
| 2023-11-07 17:16:49 | App OAuth - Google | User F          | Instance B          |
| 2023-11-05 12:08:54 | App OAuth - Google | User G          | Instance B          |
| 2023-11-04 12:54:02 | App OAuth - Google | User H          | Instance B          |
| 2023-10-29 13:06:04 | App OAuth - Google | User I          | Instance B          |
| 2023-10-22 11:57:21 | App OAuth - Google | User I          | Instance B          |
| 2023-10-19 16:28:33 | App OAuth - Google | User H          | Instance B          |
| 2023-10-17 16:46:49 | App OAuth - Google | User H          | Instance B          |
| 2023-10-15 09:56:20 | App OAuth - Google | User I          | Instance B          |
| 2023-10-13 23:35:50 | App OAuth - Google | User I          | Instance B          |
| 2023-10-12 21:51:04 | App OAuth - Google | User I          | Instance B          |
| 2023-09-26 21:31:10 | App OAuth - Google | User J          | Instance C          |
| 2023-09-24 19:17:40 | App OAuth - Google | User K          |                     |
| 2023-09-24 19:17:06 | App OAuth          | User L          |                     |
| 2023-09-24 14:11:41 | App OAuth - Google | User J          | Instance C          |
| 2023-09-18 17:45:02 | App OAuth - Google | User J          | Instance C          |
| 2023-09-17 13:01:18 | App OAuth - Google | User M          | Instance B          |
| 2023-09-15 13:09:00 | App OAuth - Google | User J          | Instance C          |
| 2023-09-15 12:55:20 | App OAuth          | User N          |                     |
| 2023-09-15 10:40:38 | App OAuth - Google | User O          | Instance C          |
| 2023-09-06 19:51:52 | App OAuth - Google | User P          | Instance B          |
| 2023-08-27 10:13:21 | App OAuth - Google | User P          | Instance B          |
| 2023-07-04 14:42:18 | App OAuth - Google | User M          | Instance B          |
| 2023-07-01 15:00:33 | App OAuth - Google | User P          | Instance B          |
| 2023-06-18 18:20:15 | App OAuth - Google | User M          | Instance B          |
| 2023-05-23 18:20:03 | App OAuth - Google | User Q          | Instance B          |
| 2023-05-01 13:36:59 | App OAuth - Google | User M          | Instance B          |
| 2023-04-21 17:27:50 | App OAuth - Google | User P          | Instance B          |

This gives us a very small number of logins (removing users with no instance):

| Month          | Number of Logins |
|----------------|------------------|
| January 2024   | 1                |
| December 2023  | 1                |
| November 2023  | 6                |
| October 2023   | 7                |
| September 2023 | 7                |
| August 2023    | 1                |
| July 2023      | 2                |
| June 2023      | 1                |
| May 2023       | 2                |
| April 2023     | 1                |

I propose to contact the administrators of Instances A, B & C - attaching the above table of logins (filtered only by their instance) asking if:

- They have a use case for the app in their instance 
- They are aware of users using them
- They think any particular communication is neccessary with their user base

But first welcoming thoughts from maintainers here

**Comment by cherry-john** [comment]
I'd be interested to hear from Instances A, B & C before making this decision, but I would agree the V1 app is ready to be retired.
It is rather challenging to maintain these days, especially as Apache Cordova is not widely used anymore. 

There is an additional question around whether the v2 app work should be continued (or restarted :) ) and whether there is appetite for an app, or whether mobile-friendly changes should be made to the existing dashboard

**Comment by adamskrz** [comment]
Is there any to assign an asset's location without the app. This was my main (intended) use for it, as we have a number of storage locations around campus, so it would be neat to be able to track where things are. I found the app was a bit clunky though, and that information is sometimes not very easy to find. I suppose an ideal workflow for me would be to pick a location, scan the tags on anything there, and then be able to filter in asset search by location (I can't remember how the app worked, and it straight up doesn't load on my new phone, I get a blank screen - Pixel 7).

**Comment by Jbithell** [comment]
I think that's the decision settled then, I propose we sunset the app at the end of the month, and I'll reach out to the instances above now to see what they think.

**Comment by Jbithell** [comment]
And to confirm, the app has been removed from stores, and the repository archived today
