### ISSUE TITLE
[PROPOSAL] Increment to v1.200 and implement a semantic versioning scheme

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#595]
This discussion proposes working towards a v1.200, and implementing semantic versioning better, to improve self-hosting experience. 

We would adopt the standard `vMAJOR.MINOR.PATCH`, but with the following scheme: 

- MAJOR *essentially not used*, remain at v1 for ease of user understanding
- MINOR version - incremented when:
  - Changes are required by a server administrator to environment variables
  - Permissions are changed/ new features added that require user engagement
  - When migrations are considered "one-way"
- PATCH version - incremented for all other releases

The intention is that server administrators would auto-update in patch versions, but not for minor versions where they would want to consult documentation

**Comment by Jbithell** [comment]
I should add that at the moment the hosted version (https://dash.adam-rms.com) builds and runs the "main" branch immediately on each push

**Comment by cherry-john** [comment]
I would argue that the things listed under MINOR version changes are intended to me MAJOR increments under semver - 'Major version [...] MUST be incremented if any backward incompatible changes are introduced..' (https://semver.org/#spec-item-8). 

However, fully agree that this would make it easier to deploy updates if this is more comprehensively defined

**Comment by Jbithell** [comment]
> I would argue that the things listed under MINOR version changes are intended to me MAJOR increments under semver - 'Major version [...] MUST be incremented if any backward incompatible changes are introduced..' (https://semver.org/#spec-item-8).

Yes definitley - we're using smver wrong - I think the choice is either to use it wrong as proposed above, or to think of it as "AdamRMS v1 version 28.3.1" if that makes sense - seperating out that this is the v1 from the actual version number

**Comment by Jbithell** [comment]
I have started to a draft release for us to collect release notes for v1.200 [here](https://github.com/adam-rms/adam-rms/releases/tag/untagged-509e2d820968216185b4)

**Comment by Jbithell** [comment]
Docs improved by @cherry-john https://github.com/adam-rms/website/pull/63

**Comment by Jbithell** [comment]
Released https://github.com/adam-rms/adam-rms/releases/tag/v1.200.0
