### ISSUE TITLE
[Docs Issue] Redo Api Documentation

### ISSUE THREAD

**Issue by cherry-john** [adam-rms/adam-rms#598]
### Page URL

https://adam-rms.com/api

### What's the Issue?

The current Api documentation is a snapshot in time and is really challenging to update.

### How should it be changed

Use a PHP api documenting package such as [Swagger-PHP](https://zircote.github.io/swagger-php/) to document the API in code, and publish a more interactive api documentation

### Anything else?

Will help fix adam-rms/website#62

**Comment by Jbithell** [comment]
Swagger-PHP does look great, but has this warning: "As of swagger-php v4 all annotations or attributes must be associated with a structural element (class, method, parameter or enum)" which might mean our filestructure doesn't quite work - as files are called directly. 

I was hoping that we could just parse your existing large json file and then spread it out into these files, but it doesn't look that simple

**Comment by cherry-john** [comment]
I've had some success using Swagger-Docs V3, which just scans the docstrings, so think there's scope there!

Looking like I might need to write a custom parser for the file, as it doesn't seem to be that widely converted...
