### ISSUE TITLE
[DOCS] Self-Hosted Startup Updated Documentation

### ISSUE THREAD

**Issue by red4dj** [adam-rms/adam-rms#605]
### What would you like the training to cover?

The hosted version is not currently accepting new users and the self-hosted docs are out of date. Even with the pre-built docker-compose I'm unable to get it up and running to start trying it out. Furthest I've gotten is the login page but I get stuck with the email verification. How is the self-hosted container supposed to send me an email verification without a SMTP setup? Am I able to use the software at all if I don't want any external cloud dependencies i.e. cloudflare or AWS?

### Is this already partially covered elsewhere?

The deprecated deployment repo and https://adam-rms.com/docs/v1/hosting/intro

**Comment by Jbithell** [comment]
Thanks for opening an issue @red4dj and for your interest in the project! 

These are some issues we're working on at the minute, with improved support for self hosting in our upcoming v1.200 release. There is a milestone to track our progress on this here: https://github.com/adam-rms/adam-rms/milestone/2

- @cherry-john has been working on documentation with a branch targeting self hosting https://github.com/adam-rms/website/tree/self-hosting-docs (preview at https://self-hosting-docs.adamrms-website.pages.dev/docs/v1/hosting/intro) but we're not quite there yet whilst we make some more fundamental changes to configuration and setup. @cherry-john - might be worth linking this issue across to your work on those docs
- I've been working on some changes to ease setup more generally - with configuration for SMTP etc. 

In terms of your specific issue of email verification - the only workaround at present is to either to create a free sendgrid api key, seed the database with the demo user `php vendor/bin/phinx seed:run` (there's some notes on that here https://adam-rms.com/docs/v1/contributor/repo/intro/#developing-locally) which will let you login, or to manually edit the database to set your email address as verified after signup. 

On the requirement for S3 compatible storage: I don't think we're likely to change this requirement for those who wish to store files (although it is currently possible to just disable file uploads), but I would like us to produce documentation for setting up [Garage](https://garagehq.deuxfleurs.fr/) in the docker environment, as this would likely be the simplest approach for users looking to avoid any cloud dependency.

**Comment by cherry-john** [comment]
We released v1.200 a few months ago that has overhauled both the self hosting process and documentation, so I hope this is sufficient! 
If not, please could you open a new issue with what else would be helpful to get adamrms up and running?
