### ISSUE TITLE
[FEATURE] Remove sendgrid dependency

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#607]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently when setting up a self-hosted instance, users must create a sendgrid api key

### Describe the solution you'd like

Be able to use SMTP as well, to reduce cloud dependency

**Comment by Jbithell** [comment]
Linked to https://github.com/adam-rms/adam-rms/issues/646

**Comment by Conshmea** [comment]
I am running into an issue when trying to selfhost that sendgrid isn't supporting new signups, Which makes the self hosted version completely unusable just now. Is there any work around or will I just have to wait until SMTP support is added?

**Comment by cherry-john** [comment]
@Conshmea I've picked this up so hoping to add some alternative providers as well as SMTP support soon.
Can't promise how fast this will be done but hoping in the next two weeks
