### ISSUE TITLE
[FEATURE] Improve self-hosting OOBE

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#610]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently the out-of-box experience for self-hosting is frustrating, requiring a great deal of setup before AdamRMS will run.

### Describe the solution you'd like

A process to guide new system administrators through the process of configuration and setting permissions

**Comment by cherry-john** [comment]
Would also be great to tweak the styling of the inital load page to make it a bit more "adamrms"
Its a bit meh :)
