### ISSUE TITLE
[FEATURE] Add flexibility to project finance calculator

### ISSUE THREAD

**Issue by adamskrz** [adam-rms/adam-rms#618]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We don't treat weekends any differently than a weekday, so if doing a hire from Sunday to Monday this would be charged by us as two days. AdamRMS calculates this as a week and a day! We have to manually override the price for each item.

### Describe the solution you'd like

I have a few ideas on how to improve the pricing system, which could protentially all be implemented:

- Add options in the business settings for how prices are generated - could include whether weekend starts/ends are treated differently, how many days creates a week rate.
- Enable a price calculation override per project, allowing the days and weeks for pricing to be manually set - this could also help where assets are being held by a client for additional days for ease of delivery/collection but are not being charged for this time
- Perhaps get rid of day->week rate calculation based on days and instead do it based on when week rates become cheaper. This could also be useful where an asset has the same price for a day and a week. Would need a lot more work on the pricing engine though.

### Describe alternatives you've considered

Having to manually override prices for every asset in each project.

**Comment by adamskrz** [comment]
I'm trying to get my head around how the week calculator currently works with weekends and it just doesn't make sense to me at all. 

For projects starting on a weekend its simple enough, if it starts on a Saturday or Sunday then the weekend is always changed as week then the rest of days as usual:
- Saturday to Sunday is 1 week
- Saturday to Monday is 1 week and 1 day
- Sunday to Monday is 1 week and 1 day

While I don't entirely understand the purpose here (I assume charging extra for having to sort crew on a weekend, given that Friday to Monday just counts as a week), I understand the behaviour.
However, there's the line in durationMaths() ```if (($end-$start) > 259200)``` for projects ending on weekends which causes some very inconsistent pricing behaviour:
- Friday to Saturday is 2 days
- Thursday to Saturday is 1 week
- Thursday to Sunday is 1 week and 2 days
- Wednesday to Saturday is 2 weeks

Is it supposed to work like this? (@Jbithell)

**Comment by Jbithell** [comment]
So sorry @adamskrz - I thought I'd responded to this. 

The current behaviour is quite York-specific but is quite well documented in that it prints out its logic behind picking that number of days & weeks in the totals tab.

![image](https://github.com/adam-rms/adam-rms/assets/8408967/fe083877-52ea-43f0-8e3c-22af2bd77202)

I suggest to keep things simple we move away from this, and allow you to specify the number of days & weeks for a given project, with a reasonable default of just the simple number of days for projects where this isn't selected. For existing projects, we can just grandfather it in via the migration.
