### ISSUE TITLE
[BUG] Draft printouts don't work in Firefox

### ISSUE THREAD

**Issue by adamskrz** [adam-rms/adam-rms#624]
### Have you contacted the support team about this?

No - I have steps to reproduce this issue, and I think I know what's causing it

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

latest

### Current Behavior

When the 'Draft Printout' button for a quote or invoice is pressed in Firefox, the projectInvoice.php tab opens then closes itself without opening the PDF. Similarly, the 'Generate PDF' button opens the tab, and the PDF is generated and uploaded but not opened. 

The only way to get a PDF is to generate one, then download it from dashboard.

### Expected Behavior

When either button is pressed, the PDF should open or download in the browser window (as happens in Chromium based browsers).

### How are you accessing AdamRMS?

https://www.whatsmybrowser.org/b/BW2FO

### Anything else?

Opening the projectInvoice.php link directly in a new tab works as expected, with the PDF opening. In the browser console there is an error about the tab not being able to close itself - so I assume in normal operation (pressing the button) the tab just closes itself before opening the PDF.

**Comment by Jbithell** [comment]
> The only way to get a PDF is to generate one, then download it from dashboard.

Can I just double check - do you mean you generate one using a chromium based browser? Or is generating working in Firefox, but not opening the PDF itself

**Comment by adamskrz** [comment]
Yep, using Firefox it does generate and upload the invoice, it just won't open (making the draft function useless).
