### ISSUE TITLE
[FEATURE] Other forms of Authentication

### ISSUE THREAD

**Issue by qubered** [adam-rms/adam-rms#641]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No, rather it's about enhancing the user authentication experience in Adam-RMS. The system currently lacks Single Sign-On options, such as OpenID Connect (OIDC) 

### Describe the solution you'd like

I would like to see support brought in for other SSO providers, such as OpenID Connect (OIDC). Personally, I manage a Microsoft tenant for my group and try, where possible, to use SSO to make life easier for my users and myself. Ideally, the features I'd like to see include:

- **OpenID Connect (OIDC)**: Integration with identity providers using OIDC would allow users to authenticate using various identity providers that support this protocol.
- **Configurable Authentication Providers**: The ability to configure and manage multiple authentication providers within Adam-RMS, offering flexibility for different organizations' needs.

Only supporting Google as an SSO option is super limiting.

**Comment by Jbithell** [comment]
@qubered thanks for suggesting this, and for your support of the project. We now support Microsoft Auth - so you can connect your microsoft login to your existing account using the "Passwords and sign in" tab at https://dash.adam-rms.com/user.php

**Comment by phil-flip** [comment]
@Jbithell Is there any chance that OIDC will be implemented?
We run our own identity provider.
