### ISSUE TITLE
[BUG] Can't create accounts if server doesn't have emails setup

### ISSUE THREAD

**Issue by cherry-john** [adam-rms/adam-rms#646]
### Have you contacted the support team about this?

No - I'm an experienced maintainer and I've found/suspect I've found root cause

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

6952b7b

### Current Behavior

The auth flow requires email addresses to be verified.
This is not possible when the server doesn't have email sending set up, so new accounts will never be enabled

### Expected Behavior

- Ability to manually verify accounts without a db edit
- Change email verification message if emails are not set up - "Contact support/server owner to enable"

**Comment by Jbithell** [comment]
Linked to https://github.com/adam-rms/adam-rms/issues/607
