### ISSUE TITLE
CMS Pages list results in slow load of user icon

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#70]
https://dash.adam-rms.com/cms/list.php

**Comment by Jbithell** [comment]
Caused by the Font Awesome Icon Picker - will require further investigation and debugging

**Comment by cherry-john** [comment]
Simple proposal to make the list page a bit faster to load:
Move the Page Configuration modal to the edit page (eg [here](https://dash.adam-rms.com/cms/edit?p=1)), as this page takes some time to load already.

Obviously this isn't an actual fix, would just make the list page faster

**Comment by cherry-john** [comment]
@Jbithell I’m no longer seeing an issue with the load time on this page, has Font Awesome updated something?

**Comment by Jbithell** [comment]
Yeah me neither, let's close this for now

**Comment by cherry-john** [comment]
This issue seems to have come back so I'm reopening this issue

**Comment by Jbithell** [comment]
Looks like package hasn't been maintained in 4 years actually :(
