### ISSUE TITLE
[FEATURE] Possibility to edit login timout

### ISSUE THREAD

**Issue by jorblad** [adam-rms/adam-rms#714]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

RIght now the timeout for being logged in atleast on the selfhosted version is incredible short, so often when I'm getting data for creating an asset or project I get logged out.

### Describe the solution you'd like

I would like to be able to decide how quick the server should be on logging users out, either on a per server or per instance basis.

**Comment by cherry-john** [comment]
Hi @jorblad
Thanks for getting involved with AdamRMS!

Just had a look into this and the session length is currently 12 hours. Are you being logged out more often than this?

**Comment by jorblad** [comment]
> Hi @jorblad
> Thanks for getting involved with AdamRMS!
> 
> Just had a look into this and the session length is currently 12 hours. Are you being logged out more often than this?

Yes more like every 5 minutes.

**Comment by cherry-john** [comment]
> Yes more like every 5 minutes.

Hmm that feels odd! I've just put this change to make this customisable so would be interesting to see if that helps.

I have a feeling your sessions are expiring based on another condition - either the IP address of the client or any proxying service changing or possibly the PHP session cookie being removed from the browser?

**Comment by jorblad** [comment]
After I added this issue I have started seeing it with other systems as well so is probably something with my proxy, web browser or simliar.
